[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.remappings]
"@openzeppelin/" = "lib/openzeppelin-contracts/contracts/"
"eas-contracts/" = "lib/eas-contracts/contracts/"
"eas-sdk" = "lib/eas-sdk/"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
